"""add_content_change_and_keyword_monitoring

Revision ID: 010a64f19c58
Revises: 6736c613bdfd
Create Date: 2026-02-04 20:57:30.983458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010a64f19c58'
down_revision: Union[str, None] = '6736c613bdfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_settings', sa.Column('content_change_detection', sa.Boolean(), nullable=True))
    op.add_column('monitoring_settings', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('monitoring_settings', sa.Column('content_selector', sa.String(length=255), nullable=True))
    op.add_column('monitoring_settings', sa.Column('last_content_check_at', sa.DateTime(), nullable=True))
    op.add_column('monitoring_settings', sa.Column('keyword_monitoring', sa.Boolean(), nullable=True))
    op.add_column('monitoring_settings', sa.Column('keywords', sa.Text(), nullable=True))
    op.add_column('monitoring_settings', sa.Column('keyword_alert_on_found', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_settings', 'keyword_alert_on_found')
    op.drop_column('monitoring_settings', 'keywords')
    op.drop_column('monitoring_settings', 'keyword_monitoring')
    op.drop_column('monitoring_settings', 'last_content_check_at')
    op.drop_column('monitoring_settings', 'content_selector')
    op.drop_column('monitoring_settings', 'content_hash')
    op.drop_column('monitoring_settings', 'content_change_detection')
    # ### end Alembic commands ###
