"""add custom_headers to projects

Revision ID: 4bab6c85127f
Revises: 010a64f19c58
Create Date: 2026-02-04 21:07:06.489554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bab6c85127f'
down_revision: Union[str, None] = '010a64f19c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('custom_headers', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'custom_headers')
    # ### end Alembic commands ###
