"""add_maintenance_mode_to_project

Revision ID: 6736c613bdfd
Revises: e7a3b5c9d2f1
Create Date: 2026-02-04 20:43:38.880279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6736c613bdfd'
down_revision: Union[str, None] = 'e7a3b5c9d2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('maintenance_mode', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('maintenance_message', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('maintenance_started_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('maintenance_ends_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'maintenance_ends_at')
    op.drop_column('projects', 'maintenance_started_at')
    op.drop_column('projects', 'maintenance_message')
    op.drop_column('projects', 'maintenance_mode')
    # ### end Alembic commands ###
