"""Add category and tags to project

Revision ID: 930d4be4c186
Revises: e2e03e4cbc9d
Create Date: 2026-01-28 21:16:11.341867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930d4be4c186'
down_revision: Union[str, None] = 'e2e03e4cbc9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('tags', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'tags')
    op.drop_column('projects', 'category')
    # ### end Alembic commands ###
