"""add_playwright_metrics_to_monitoring_logs

Revision ID: fb52c0c8a942
Revises: af916e15dfe0
Create Date: 2026-01-26 21:27:19.893477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb52c0c8a942'
down_revision: Union[str, None] = 'af916e15dfe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_logs', sa.Column('check_type', sa.String(length=20), nullable=True))
    op.add_column('monitoring_logs', sa.Column('dom_content_loaded', sa.Float(), nullable=True))
    op.add_column('monitoring_logs', sa.Column('page_load_time', sa.Float(), nullable=True))
    op.add_column('monitoring_logs', sa.Column('first_contentful_paint', sa.Float(), nullable=True))
    op.add_column('monitoring_logs', sa.Column('largest_contentful_paint', sa.Float(), nullable=True))
    op.add_column('monitoring_logs', sa.Column('js_errors', sa.Text(), nullable=True))
    op.add_column('monitoring_logs', sa.Column('console_errors', sa.Integer(), nullable=True))
    op.add_column('monitoring_logs', sa.Column('resource_count', sa.Integer(), nullable=True))
    op.add_column('monitoring_logs', sa.Column('resource_size', sa.Integer(), nullable=True))
    op.add_column('monitoring_logs', sa.Column('is_dom_ready', sa.Boolean(), nullable=True))
    op.add_column('monitoring_logs', sa.Column('is_js_healthy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitoring_logs', 'is_js_healthy')
    op.drop_column('monitoring_logs', 'is_dom_ready')
    op.drop_column('monitoring_logs', 'resource_size')
    op.drop_column('monitoring_logs', 'resource_count')
    op.drop_column('monitoring_logs', 'console_errors')
    op.drop_column('monitoring_logs', 'js_errors')
    op.drop_column('monitoring_logs', 'largest_contentful_paint')
    op.drop_column('monitoring_logs', 'first_contentful_paint')
    op.drop_column('monitoring_logs', 'page_load_time')
    op.drop_column('monitoring_logs', 'dom_content_loaded')
    op.drop_column('monitoring_logs', 'check_type')
    # ### end Alembic commands ###
